/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs.index'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests.index'
import { Route as AuthenticatedTestsIdRouteImport } from './routes/_authenticated/tests.$id'
import { Route as AuthenticatedTestsNewRouteImport } from './routes/_authenticated/tests.new'
import { Route as AuthenticatedRunsIdIndexRouteImport } from './routes/_authenticated/runs.$id.index'
import { Route as AuthenticatedRunsIdReportRouteImport } from './routes/_authenticated/runs.$id.report'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo/webhook'
import { Route as ApiPublicWorkerAiRouteImport } from './routes/api/public/worker/ai'
import { Route as ApiPublicWorkerEventsRouteImport } from './routes/api/public/worker/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsIdRoute = AuthenticatedTestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsNewRoute = AuthenticatedTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIdIndexRoute =
  AuthenticatedRunsIdIndexRouteImport.update({
    id: '/runs/$id/',
    path: '/runs/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRunsIdReportRoute =
  AuthenticatedRunsIdReportRouteImport.update({
    id: '/runs/$id/report',
    path: '/runs/$id/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo/webhook',
  path: '/api/public/dodo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerAiRoute = ApiPublicWorkerAiRouteImport.update({
  id: '/api/public/worker/ai',
  path: '/api/public/worker/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerEventsRoute = ApiPublicWorkerEventsRouteImport.update({
  id: '/api/public/worker/events',
  path: '/api/public/worker/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/tests/$id': typeof AuthenticatedTestsIdRoute
  '/tests/new': typeof AuthenticatedTestsNewRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/runs/$id/report': typeof AuthenticatedRunsIdReportRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/worker/ai': typeof ApiPublicWorkerAiRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/runs/$id/': typeof AuthenticatedRunsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/tests/$id': typeof AuthenticatedTestsIdRoute
  '/tests/new': typeof AuthenticatedTestsNewRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/runs/$id/report': typeof AuthenticatedRunsIdReportRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/worker/ai': typeof ApiPublicWorkerAiRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/runs/$id': typeof AuthenticatedRunsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/tests/$id': typeof AuthenticatedTestsIdRoute
  '/_authenticated/tests/new': typeof AuthenticatedTestsNewRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_authenticated/runs/$id/report': typeof AuthenticatedRunsIdReportRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/worker/ai': typeof ApiPublicWorkerAiRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/_authenticated/runs/$id/': typeof AuthenticatedRunsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/r/$token'
    | '/projects/$id'
    | '/tests/$id'
    | '/tests/new'
    | '/projects/'
    | '/runs/'
    | '/tests/'
    | '/runs/$id/report'
    | '/api/public/dodo/webhook'
    | '/api/public/worker/ai'
    | '/api/public/worker/events'
    | '/runs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/r/$token'
    | '/projects/$id'
    | '/tests/$id'
    | '/tests/new'
    | '/projects'
    | '/runs'
    | '/tests'
    | '/runs/$id/report'
    | '/api/public/dodo/webhook'
    | '/api/public/worker/ai'
    | '/api/public/worker/events'
    | '/runs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/r/$token'
    | '/_authenticated/projects/$id'
    | '/_authenticated/tests/$id'
    | '/_authenticated/tests/new'
    | '/_authenticated/projects/'
    | '/_authenticated/runs/'
    | '/_authenticated/tests/'
    | '/_authenticated/runs/$id/report'
    | '/api/public/dodo/webhook'
    | '/api/public/worker/ai'
    | '/api/public/worker/events'
    | '/_authenticated/runs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  ApiPublicWorkerAiRoute: typeof ApiPublicWorkerAiRoute
  ApiPublicWorkerEventsRoute: typeof ApiPublicWorkerEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$id': {
      id: '/_authenticated/tests/$id'
      path: '/tests/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof AuthenticatedTestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/new': {
      id: '/_authenticated/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof AuthenticatedTestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$id/': {
      id: '/_authenticated/runs/$id/'
      path: '/runs/$id'
      fullPath: '/runs/$id/'
      preLoaderRoute: typeof AuthenticatedRunsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$id/report': {
      id: '/_authenticated/runs/$id/report'
      path: '/runs/$id/report'
      fullPath: '/runs/$id/report'
      preLoaderRoute: typeof AuthenticatedRunsIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/dodo/webhook': {
      id: '/api/public/dodo/webhook'
      path: '/api/public/dodo/webhook'
      fullPath: '/api/public/dodo/webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/ai': {
      id: '/api/public/worker/ai'
      path: '/api/public/worker/ai'
      fullPath: '/api/public/worker/ai'
      preLoaderRoute: typeof ApiPublicWorkerAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/events': {
      id: '/api/public/worker/events'
      path: '/api/public/worker/events'
      fullPath: '/api/public/worker/events'
      preLoaderRoute: typeof ApiPublicWorkerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedTestsIdRoute: typeof AuthenticatedTestsIdRoute
  AuthenticatedTestsNewRoute: typeof AuthenticatedTestsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
  AuthenticatedRunsIdReportRoute: typeof AuthenticatedRunsIdReportRoute
  AuthenticatedRunsIdIndexRoute: typeof AuthenticatedRunsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedTestsIdRoute: AuthenticatedTestsIdRoute,
  AuthenticatedTestsNewRoute: AuthenticatedTestsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
  AuthenticatedRunsIdReportRoute: AuthenticatedRunsIdReportRoute,
  AuthenticatedRunsIdIndexRoute: AuthenticatedRunsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  ApiPublicWorkerAiRoute: ApiPublicWorkerAiRoute,
  ApiPublicWorkerEventsRoute: ApiPublicWorkerEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
